### ISSUE TITLE
Some tests are timed wrongly

### ISSUE THREAD

**Issue by andyw8** [knzai/test_benchmark#5]
My test suite takes a long time to run but certainly not as long as the report claims (5000 hours+).

Perhaps an overflow somewhere?

Truncated output:

18255421.188 test: A player who...
5270400.459 test: Given a player ..
3888000.499 test: Given a player achieves...
3888000.337 test: Given a player achieves...
3888000.182 test: Given a player achieves...
600.029 test: Given an active ...
7.911 test: when getting JSON data ...
4.606 test: when getting JSON data ...
4.353 test: when getting JSON data ...
4.287 test: when getting JSON data ...

Gemfile:

source :rubygems

gem "rails", "2.3.8"
gem "mysql", "2.8.1"
gem "fastercsv", "1.5.1"
gem "json", "1.4.3"
gem "authlogic", "2.1.3"
gem "haml", "2.2.21"
gem "compass", "0.8.17"
gem "daemons", "1.0.10"
gem "colorist", "0.0.2"
gem "hoptoad_notifier", "2.3.2"
gem "mechanize", "0.9.3"
gem "typhoeus", "0.1.23"
gem "hpricot", "0.8.2"
gem "flickr_fu", "0.3.0"
gem "htmlentities", "4.0.0"
gem "sprockets", "1.0.2"
gem "oauth", "0.3.6"
gem 'aws-s3', '0.6.2'
gem 'RedCloth', '4.2.3'
gem "oauth2", "0.0.13"

group :test do
  gem "factory_girl", "1.2.3"
  gem "shoulda", "2.10.3"
  gem "mocha", "0.9.8"
  gem "webrat", "0.7.1"
  gem "webmock", "0.9.1", :require => nil
  gem "timecop", "0.3.5"
  gem "ruby-debug", "0.10.3"
  gem "launchy", "0.3.7"
  gem "test_benchmark", :git => 'git://github.com/timocratic/test_benchmark.git'
end

**Comment by knzai** [comment]
I'm not really maintaining this anymore since I don't generally use test-unit anymore.

**Comment by andyw8** [comment]
I found that the problem was due to Timecop not being reset.
